import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { countBy } from "./collections.ts";
import { codeGraphJsonSchema, codeGraphSnapshotSchema } from "./schema.ts";
import { summarizeGraph } from "./query.ts";
import type { CodeGraphSnapshot, WriteCodeGraphOptions } from "./types.ts";

export async function writeCodeGraphArtifacts(graph: CodeGraphSnapshot, options: WriteCodeGraphOptions): Promise<void> {
	const parsed = codeGraphSnapshotSchema.parse(graph);
	await mkdir(options.outDir, { recursive: true });
	await Bun.write(join(options.outDir, "schema.json"), `${JSON.stringify(codeGraphJsonSchema(), null, 2)}\n`);
	await Bun.write(join(options.outDir, "manifest.json"), `${JSON.stringify(parsed.manifest, null, 2)}\n`);
	await Bun.write(join(options.outDir, "graph.json"), `${JSON.stringify(parsed, null, 2)}\n`);
	const mapPath = options.mapPath ?? join(options.outDir, "CODEBASE_MAP.md");
	await mkdir(dirname(mapPath), { recursive: true });
	await Bun.write(mapPath, renderMap(parsed));
}

export async function readCodeGraph(outDir: string): Promise<CodeGraphSnapshot> {
	const graphPath = join(outDir, "graph.json");
	const raw = await Bun.file(graphPath).json();
	return codeGraphSnapshotSchema.parse(raw);
}

export function renderMap(graph: CodeGraphSnapshot): string {
	const filesByKind = countBy(
		graph.nodes.filter((node) => node.kind === "File" || node.kind === "Doc" || node.kind === "GeneratedArtifact"),
		(node) => String(node.metadata["fileKind"] ?? node.kind),
	);
	const packages = graph.nodes.filter((node) => node.kind === "Package");
	const scripts = graph.nodes.filter((node) => node.kind === "PackageScript");
	const envVars = graph.nodes.filter((node) => node.kind === "EnvVar");
	const iacNodes = graph.nodes.filter((node) => node.kind === "IaCResource" || node.kind === "IaCModule");
	const dbNodes = graph.nodes.filter((node) => node.kind.startsWith("Db"));
	return [
		"# Codebase Map",
		"",
		"Generated by Cartographer code graph.",
		"",
		"## Summary",
		"",
		`\`\`\`text\n${summarizeGraph(graph).trim()}\n\`\`\``,
		"",
		"## File Mix",
		...Object.entries(filesByKind).map(([kind, count]) => `- ${kind}: ${count}`),
		"",
		"## Packages",
		...renderNodeList(packages, (node) => `- ${node.label} - \`${node.path ?? node.id}\``),
		"",
		"## Package Scripts",
		...renderNodeList(scripts, (node) => `- ${node.label}: \`${String(node.metadata["command"] ?? "")}\``),
		"",
		"## Environment Variables",
		...renderNodeList(envVars, (node) => `- ${node.label}`),
		"",
		"## Database And IaC",
		...renderNodeList(
			[...dbNodes, ...iacNodes],
			(node) => `- ${node.kind}: ${node.label} - \`${node.path ?? node.id}\``,
		),
		"",
		"## Findings",
		...(graph.findings.length === 0
			? ["- None"]
			: graph.findings.map((finding) => `- ${finding.severity}: ${finding.message}`)),
		"",
		"## Agent Notes",
		"",
		"Use `cartographer annotate` to generate candidate semantic overlay notes. Agent annotations are not canonical graph facts until reviewed.",
		"",
	].join("\n");
}

function renderNodeList<T>(nodes: readonly T[], renderNode: (node: T) => string): readonly string[] {
	return nodes.length === 0 ? ["- None detected"] : nodes.map(renderNode);
}
